cell_width: 20
cell_height: 20
map: |
    -----------------------------------------------------------------------------------
    -----------------------------------------------------------------------------------
    -----------WWWWWWWWWWWWWWWWWWWW-----a-a------b-------------------------------------
    ----b------W-----------------------------------------------------------------------
    -----------W-----a----------------------------------------m------------------------
    -----------W--------------------------------------------------------------WW-------
    -----------W------------------------------------------------aa------------WW---a---
    -----------W--------------aa-----------m----------------------------------WW---a---
    -----------W--------------aa--------------------------WWWWWWWWWWWWWWWWWWWWWW---a---
    -----------W--------------------------------------------------------------WW---a---
    -----------W--------------------------------------------------------------WW---a---
    -----------W--------------------------------------------------------------WW-------
    -----------W---------------aWWWWWWWWWWWWWWWW------------------------------WW-------
    -----------------------------------------------------a-a-a----------------WW-------
    --------------------------------------------------------------------------WW-------
    --------------------------------------------------------------------------WW-------
    ----------------------------------------c---------------------------------WW---b---
    -----------------------------------------------------a-a------------------WW---b---
    ---------------------------------------------------------------S----------WW-------
    -------------------a------------------------------------------------------WW-------
    ---b----------------------------------------------------------------------WW-------
    --------------------------------------------------------------------------WW-------
    --------------------------------------------------------------------------WW-------
    ---------------W-------------------------------------------------------------------
    ---------------W-------------------------------------------------------------------
    ------m--------W-------------------------------------------------------------------
    ---------------W-----------------------------------------WWWWWWWWWWWWWWWWWWWWWW----
    ---------------W-------b---------------------------------WWWWWWWWWWWWWWWWWWWWWW----
    ---------------W-------------------------------------------------------------------
    ---------------W---------------------------------------S---------------------------
    ---------------W---------------------------------------------------------a---------
    ---------------WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW------------------b---------
    -----------------------------------------------------------------------------------
    -----------------------------------------------------------------------------------
    -----------------------------------------------------------------------------------
    -----------------------------------------------------------------------------------
    -------S--------------------------------------m----------------bbbbbbbb------------
    -----------------------------------------------------------------------------------
    --------------------------------------------------------WWWWWWWWWWWWWWWWWWWWWWWWWWW
    S-----------------------------WWWWWWWWWWWWWWWW-------------------------------------
    ---------------------------------aaaaaa------W----------------aaaaaaaa-------------
    ---------------m-----------------------------W----------------aaaaaaaa-------------
    ---------------------------------------------W----------------aaaaaaaa-------------
    ---------------------------------------------W----------------aaaaaaaa-------------
    